module.exports = {
  moduleFileExtensions: ["js", "json", "ts"],
  rootDir: "src",
  testRegex: ".*\\.spec\\.ts$",
  setupFilesAfterEnv: ["<rootDir>/../jest.setup.js"],
  transform: {
    "^.+\\.(t|j)s$": "ts-jest",
  },
  collectCoverageFrom: [
    "**/*.(t|j)s",
    "!**/*.spec.ts",
    "!**/*.interface.ts",
    "!**/*.dto.ts",
    "!**/*.module.ts",
    "!**/main.ts",
    "!**/prisma.service.ts",
    "!**/test-helpers/**",
    "!**/patient-utils.service.ts",
    "!**/health.controller.ts",
    "!**/messages.controller.ts",
    "!**/messages.gateway.ts",
    "!**/guards/ws-jwt.guard.ts",
    "!**/notifications.controller.ts",
    "!**/realtime-notifications.service.ts",
    "!**/reports.controller.ts",
    "!**/insulin-doses.service.ts",
    "!**/node_modules/**",
    "!**/dist/**",
  ],
  coverageDirectory: "../coverage",
  testEnvironment: "node",
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
    "^@glucosapp/env$": "<rootDir>/../../../packages/env/src/index.ts",
    "^@glucosapp/types$": "<rootDir>/../../../packages/types/src/index.ts",
    "^@glucosapp/(.*)$": "<rootDir>/../../../packages/$1/src",
    "^@glucosapp/mdi-insulin-algorithm$":
      "<rootDir>/../../../../mdi-insulin-algorithm/dist/index.cjs",
    "^mdi-insulin-algorithm$": "<rootDir>/../../../../mdi-insulin-algorithm/dist/index.cjs",
  },
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 82,
      lines: 82,
      statements: 82,
    },
  },
  coverageReporters: ["text", "json", "html", "lcov"],
  testTimeout: 10000,
  maxWorkers: process.env.CI ? 2 : "50%",
};
