-- AlterTable
ALTER TABLE "User" ADD COLUMN     "mealTimeBreakfastEnd" INTEGER NOT NULL DEFAULT 660,
ADD COLUMN     "mealTimeBreakfastStart" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "mealTimeDinnerEnd" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "mealTimeDinnerStart" INTEGER NOT NULL DEFAULT 1020,
ADD COLUMN     "mealTimeLunchEnd" INTEGER NOT NULL DEFAULT 1020,
ADD COLUMN     "mealTimeLunchStart" INTEGER NOT NULL DEFAULT 660;
