-- AlterTable
ALTER TABLE "User" ADD COLUMN "carbRatio" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN "insulinSensitivityFactor" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "targetGlucose" INTEGER;

